project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"
  

website:
  title: "Elements of Data Analysis and Statistics - Lab Exercises"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Labs
        contents:
          - qmd/01-pivot-tables-with-libreoffice.qmd
          - qmd/03-discharge-elbe.qmd
          - qmd/04-distributions-leaves.qmd
          - qmd/05-distributions-fruits-tidyverse.qmd
          - qmd/06-classical-tests.qmd
          - qmd/07-correlation.qmd
          - qmd/08-vollenweider-chl-tp.qmd
          - qmd/09-clementines-anova.qmd
          - qmd/10-nonlinear-regression.qmd
          - qmd/12-timeseries-trends.qmd
          - qmd/13-timeseries-breakpoints.qmd
          - qmd/14-flood-risk.qmd
          - qmd/15-multivariate-small-streams.qmd
      - section: Projects
        contents:
          - qmd/03-discharge-elbe-project.qmd
      - section: Solutions
        contents:
          - qmd/10-nonlinear-regression-solution.qmd
          
format:
  html:
    theme: cosmo
    css: thpe.css
    toc: true
    number-sections: true
    #embed-resources: true
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm
bibliography: bib.bib
csl: apa.csl

execute:
  freeze: auto